#!/bin/bash

# Credit:
# While this file was heavily modified by the NetCore j.s.a. team, it's based on this original file
# https://orrsella.com/2014/11/06/initd-and-start-scripts-for-scala-java-server-apps

### BEGIN INIT INFO
# Provides:          <|service_name|>
# Required-Start:    $network $local_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: <|short_description|>
# Description:       <|long_description|>
### END INIT INFO

# Application .jar path
APP_JAR="<|binary_path|>"

# Application start options
APP_OPTS=`cat /etc/default/<|service_name|> 2> /dev/null`

# Application run command
DAEMON="java $APP_OPTS -jar $APP_JAR"

# PID file location
PID_FILE="/var/run/<|service_name|>.pid"

# colors
red='\e[0;31m'
green='\e[0;32m'
yellow='\e[0;33m'
reset='\e[0m'

echoRed() { echo -e "${red}$1${reset}"; }
echoGreen() { echo -e "${green}$1${reset}"; }
echoYellow() { echo -e "${yellow}$1${reset}"; }

start() {
    echo "Attempting to start <|product_name|>..."
    PID=`$DAEMON &> /dev/null & echo $!`

    sleep 3
    if [ -z "`ps axf | grep -w ${PID} | grep -v grep`" ]; then
        PID=""
    fi
}

case "$1" in
start)
    if [ -f $PID_FILE ]; then
        PID=`cat $PID_FILE`
        if [ -z "`ps axf | grep -w ${PID} | grep -v grep`" ]; then
            start
        else
            echoYellow "<|product_name|> is already running - PID $PID"
            exit 0
        fi
    else
        start
    fi

    if [ -z $PID ]; then
        echoRed "<|product_name|> failed to start"
        echo "Try running '$DAEMON' and check for errors"
        rm -f $PID_FILE
        exit 3
    else
        echo $PID > $PID_FILE
        echoGreen "<|product_name|> is now starting - PID $PID"
        exit 0
    fi
;;

status)
    if [ -f $PID_FILE ]; then
        PID=`cat $PID_FILE`
        if [ -z "`ps axf | grep -w ${PID} | grep -v grep`" ]; then
            echoRed "<|product_name|> is not running (process dead but pidfile exists)"
            exit 1
        else
            echoGreen "<|product_name|> is running - PID $PID"
            exit 0
        fi
    else
        echoRed "<|product_name|> is not running"
        exit 3
    fi
;;

stop)
    if [ -f $PID_FILE ]; then
        PID=`cat $PID_FILE`
        if [ -z "`ps axf | grep -w ${PID} | grep -v grep`" ]; then
            echoRed "<|product_name|> is not running (process dead but pidfile exists)"
            exit 1
        else
            PID=`cat $PID_FILE`
            kill -HUP $PID
            echoGreen "<|product_name|> stopped - PID was $PID"
            rm -f $PID_FILE
            exit 0
        fi
    else
        echoRed "<|product_name|> is not running (pid not found)"
        exit 3
    fi
;;

restart)
    $0 stop
    $0 start
;;

*)
    echo "Usage: $0 {status|start|stop|restart}"
    exit 1
esac
